language: python
python:
  - 2.7

services:
  - redis-server

install:
  - pip install -r src/web/requirements.txt --use-mirrors
  - pip install -r src/bridge/requirements.txt --use-mirrors
  - pip install -r src/monitors/requirements.txt --use-mirrors
  - pip install coverage
  - pip install coveralls
#  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - echo "deb http://download.rethinkdb.com/apt `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb --force-yes
  - rethinkdb --version

before_script:
  - rethinkdb &
  - rethinkdb admin set auth cloudroutes
  - cp src/web/instance/web.cfg.default src/web/instance/web.cfg
  - python src/bridge/mgmtscripts/create_db.py src/bridge/config/config.yml.default
  - python src/web/web.py &

script:
  - python src/web/tests.py
  - coverage run src/web/test.py

after_success:
  coveralls