site_name: Runbook Docs
site_url: https://www.runbook.io/
site_description:
site_favicon: 
theme: readthedocs

pages:
- ['index.md', 'Overview']
- ['quick-start.md', 'Quick Start']
- ['api.md', 'API']
- ['monitors/index.md', 'Monitors', 'Overview']
- ['monitors/network-availability.md', 'Monitors', "Network Availability"]
- ['monitors/web-applications.md', 'Monitors', "Web Applications"]
- ['monitors/ssl.md', 'Monitors', "SSL Certificates"]
- ['monitors/heroku.md', 'Monitors', "Heroku"]
- ['monitors/digitalocean.md', 'Monitors', "DigitalOcean"]
- ['monitors/datadog.md', 'Monitors', "Datadog"]
- ['monitors/papertrail.md', 'Monitors', "Papertrail"]
- ['monitors/logentries.md', 'Monitors', "Logentries"]
- ['monitors/runbook-webhooks.md', 'Monitors', "Runbook Webhooks"]
- ['reactions/index.md', 'Reactions', 'Overview']
- ['reactions/cloudflare.md', 'Reactions', 'CloudFlare']
- ['reactions/heroku.md', 'Reactions', 'Heroku']
- ['reactions/commando.md', 'Reactions', 'Commando']
- ['reactions/digitalocean.md', 'Reactions', 'DigitalOcean']
- ['reactions/aws.md', 'Reactions', 'AWS']
- ['reactions/rackspace.md', 'Reactions', 'Rackspace']
- ['reactions/saltstack.md', 'Reactions', 'Saltstack']
- ['reactions/notifications.md', 'Reactions', 'Notifications']
- ['reactions/statistics.md', 'Reactions', 'Statistics']
- ['developers/index.md', 'Developers', 'Overview']
- ['developers/architecture-overview.md', 'Developers', 'Architecture Overview']
- ['developers/install.md', 'Developers', 'Installation']
- ['developers/install_docker.md', 'Developers', 'Installation with Docker'] 
- ['developers/creating_monitors.md', 'Developers', 'Creating Monitors']
- ['developers/creating_reactions.md', 'Developers', 'Creating Reactions']
- ['community-tutorials/index.md', 'Community Tutorials']
